openapi: 3.0.0
info:
  title: Sample API
  description: Description global de API TEST.
  version: 0.1.9
servers:
  - url: http://host.docker.internal:8080/v1/
    description: Optional server description, e.g. Main (production) server
  - url: http://host.docker.internal:8080/v1/
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /status:
    get:
      summary: Returns the site status.
      description: Returns the site status.
      responses:
        '200':    # status code
          description: A JSON of site status
          content:
            application/json:
              schema: 
                type: string
